### ISSUE TITLE
Environment variables are not being used in configuration

### ISSUE THREAD

**Issue by jordanjennings** [SUSE/Portus#1386]
On the latest head image, some environment variables aren't working to control the configuration. For example, I have `PORTUS_MACHINE_FQDN_VALUE=portus.mydomain.com` but it's still got `portus.test.lan` configured and so my registry won't trust it.

The LDAP configuration also doesn't work via environment variables. The DB configuration _does_ appear to work though.

How can I see the full active configuration that Portus is using to tell what else is not working? I'm configuring the instance entirely with environment variables, and if I exec into the running container i see everything expected when running `env`. What other information can I provide to help troubleshoot?

**Comment by Vad1mo** [comment]
set the prefix `CCONFIG=PORTUS` you can see the final config with `rake cconfig:info`

**Comment by jordanjennings** [comment]
@Vad1mo Thanks for the fast response!  Where can I run that rake command inside the running container? I tried in /srv/Portus but got:

```
bash-4.3# rake cconfig:info
rake aborted!
cannot load such file -- bundler/setup
/srv/Portus/config/boot.rb:3:in `<top (required)>'
/srv/Portus/config/application.rb:1:in `<top (required)>'
/srv/Portus/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
```

I also tried setting CCONFIG=PORTUS but that doesn't seem to have changed anything. Doing more testing still...

**Comment by Vad1mo** [comment]
`rake cconfig:info` should be executed in the portus project root dir.

**Comment by jordanjennings** [comment]
@Vad1mo yes I'm using `opensuse/portus:head`, sorry should have stated more clearly above

**Comment by jordanjennings** [comment]
@Vad1mo what is the "portus project root dir (WORKDIR)" inside the `opensuse/portus:head` container? is there one? or is there any other way I can try to debug why the environment variables are not being used for the configuration? I am not familiar with rails configs, so not sure where to start looking.

**Comment by Vad1mo** [comment]
it should be /srv/Portus it seems like the dockerfile is not uptodate with the current code. I would stick to 2.2 in your case.

**Comment by jordanjennings** [comment]
Darn, I got everything set up on Kubernetes with head so we could use the security scanning integration. Been working great until now. Maybe I'll tag an older head build that wasn't broken and use it instead. I'll leave this issue open because this should still be addressed when possible.

**Comment by Vad1mo** [comment]
when you have everything working then you should also be able to execute `rake` in /srv/Portus and  env var CCONFIG=PORTUS should kick in.  However I think that with the migration to vue there the current dockerfile need a some updates. However I might be wrong, as I am not using it.

**Comment by generationtech** [comment]
I did notice similar effect in troubleshooting my [#1388](https://github.com/SUSE/Portus/issues/1388)

When I switched to using the "Insecure Example" production configuration from the Github source, the Portus server insisted on needing SSL (admin webpage error) even though the configuration option 

`PORTUS_CHECK_SSL_USAGE_ENABLED: 'false'`

was set. Sounds similar to the kinds of problem @jordanjennings is having

**Comment by jordanjennings** [comment]
@generationtech just as a temporary fix you can use a "cached" version of head that I put up on Docker Hub at jordanjennings/portus:head-working, it's from a couple weeks back (not 100% sure on the date but it has security scanning working which is what I was interested in).

**Comment by generationtech** [comment]
Thanks for that referral. I tried it and still have the problem registering an SSL registry, whether using Letsencrypt certs or self-signed. I guess I will continue working it in that other issue thread

**Comment by generationtech** [comment]
BUT, I can now use the "Insecure Example" production configuration from the Github source by using your cached version of head. So apparently that helps with getting the SSL bypass environment variable into the Portus image similar to your environment var problem. Much appreciated! I'm still gonna need to fix my SSL, but at least I can test Portus now.

**Comment by mssola** [comment]
This is a duplicate of #1418. I'll come back to this once that issue is fixed. Sorry for the inconvenience... 😞

**Comment by mssola** [comment]
This is fixed. Open again if this is not the case for you (pull the image again, and bear in mind the new env. variables to be used, we'll provide more documentation shortly).

**Comment by suntorytimed** [comment]
The problem still persists for me. At least the LDAP env variables aren't used:
- PORTUS_LDAP_ENABLED='true'
- PORTUS_LDAP_HOSTNAME="xxx.yyy.de"
- PORTUS_LDAP_BASE="ou=dir,o=xxx,c=de"

**Comment by mssola** [comment]
@suntorytimed this shouldn't really happen anymore :confused: Let's see:

- Which version are you using ? If it's a docker image, when did you pulled it (make sure it hasn't been cached) ?
- Are you setting the `CCONFIG_PREFIX` as specified on the examples ?
- What does `portusctl exec rake portus:info` return ?
- Do you have some logs ?

**Comment by suntorytimed** [comment]
What appears strange to me is, that `portusctl exec rake portus:info` does indeed show that LDAP is active, but the login page ignores the setting. As soon as I use a config-local.yaml it does work.

* I've tried :latest and :head with tag cffa081d8347 (latest) and fa9504bf8ed1 (head)
* `CCONFIG_PREFIX=PORTUS`
* Output of `portusctl exec rake portus:info`:
```
[Mailer config] Host:     kvm-lodock.tvc.yyy.de
[Mailer config] Protocol: https://
Evaluated configuration:
---
email:
  from: portus@example.com
  name: Portus
  reply_to: ''
  smtp:
    enabled: false
    address: smtp.example.com
    port: 587
    user_name: username@example.com
    password: "****"
    domain: example.com
gravatar:
  enabled: true
delete:
  enabled: true
  contributors: false
ldap:
  enabled: "'true'"
  hostname: '"xxx.yyy.de"'
  port: 389
  method: plain
  base: '"ou=dir,o=xxx,c=de"'
  filter: ''
  uid: uid
  authentication:
    enabled: false
    bind_dn: ''
    password: "****"
  guess_email:
    enabled: "'true'"
    attr: ''
oauth:
  local_login:
    enabled: true
  google_oauth2:
    enabled: false
    id: ''
    secret: ''
    domain: ''
    options:
      hd: ''
  open_id:
    enabled: false
    identifier: ''
    domain: ''
  github:
    enabled: false
    client_id: ''
    client_secret: ''
    organization: ''
    team: ''
    domain: ''
  gitlab:
    enabled: false
    application_id: ''
    secret: ''
    group: ''
    domain: ''
    server: ''
  bitbucket:
    enabled: false
    key: ''
    secret: ''
    domain: ''
    options:
      team: ''
first_user_admin:
  enabled: true
signup:
  enabled: true
check_ssl_usage:
  enabled: true
registry:
  jwt_expiration_time:
    value: 5
  catalog_page:
    value: 100
  timeout:
    value: 2
  read_timeout:
    value: 120
machine_fqdn:
  value: kvm-lodock.tvc.yyy.de
display_name:
  enabled: false
user_permission:
  change_visibility:
    enabled: true
  create_team:
    enabled: true
  manage_team:
    enabled: true
  create_namespace:
    enabled: true
  manage_namespace:
    enabled: true
  push_images:
    enabled: true
security:
  clair:
    server: ''
    health_port: 6061
  zypper:
    server: ''
  dummy:
    server: ''
anonymous_browsing:
  enabled: true
background:
  registry:
    enabled: true
  sync:
    enabled: true
    strategy: initial

Portus version: 2.4.0-dev@f9bee43f97421ea42abab53f0ae33527e9e66cd3
```
* just tell me what kind of logs you need and I will provide them
