### ISSUE TITLE
webhook events -  no route to host, retrying

### ISSUE THREAD

**Issue by OBenned** [SUSE/Portus#1496]
Hello.

Im using the docker-compose example, with SSL enabled.
The only exception from the example is that i use mssola/portus:susecon image for the portus container, since i could not get opensuse/portus working (both head and 2.2)

The problem i have right now is that when i push an image to my registry, i get the following error from the registry.

`registry_1  | time="2017-10-31T12:34:05Z" level=error msg="retryingsink: error writing events: httpSink{https://registry.flexgateway.io/v2/webhooks/events}: error posting: Post https://registry.flexgateway.io/v2/webhooks/events: dial tcp 91.217.201.167:443: getsockopt: no route to host, retrying"
registry_1  | time="2017-10-31T12:34:05Z" level=warning msg="httpSink{https://registry.flexgateway.io/v2/webhooks/events} encountered too many errors, backing off"
`

There is no problem with login to the registry, it only seems like webhooks is broken right now for me

**Comment by Vad1mo** [comment]
seems like the registry isn't able to connect to https://registry.flexgateway.io/v2/webhooks/events

can you enter you registry container `docker exec -ti registry`and do a `curl` or `curl -I` on `https://registry.flexgateway.io/v2/webhooks/events`  this way you can find out if the registry is able to reach https://registry.flexgateway.io/v2/webhooks/events

**Comment by OBenned** [comment]
Since the docker registry image doesent contain curl i, tried running this from the local docker machine and im getting this with curl -I https://registry.flexgateway.io/v2/webhooks/events

`HTTP/1.1 404 Not Found
Server: nginx
Date: Tue, 31 Oct 2017 12:56:43 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Request-Id: ca4ade4d-725b-4176-be9b-8b7329879dca
X-Runtime: 0.014596
`

**Comment by Vad1mo** [comment]
this indicates me that https://registry.flexgateway.io/v2/webhooks/events is not reachable. Check your nginx config. I also can't curl to https://registry.flexgateway.io/v2/webhooks/events.

You can change to config of registry to send the data to the interal container DNS. if you use the current docker-compsoe.yaml from master the dns name is simpel `portus:3000`

**Comment by OBenned** [comment]
Just tried with the internal container, then i get a connection refused:

`registry_1  | time="2017-10-31T13:10:06Z" level=error msg="retryingsink: error writing events: httpSink{https://portus/v2/webhooks/events}: error posting: Post https://portus/v2/webhooks/events: dial tcp 172.19.0.4:443: getsockopt: connection refused, retrying"
registry_1  | time="2017-10-31T13:10:06Z" level=warning msg="httpSink{https://portus/v2/webhooks/events} encountered too many errors, backing off"`

**Comment by Vad1mo** [comment]
http not http port 3000

**Comment by OBenned** [comment]
Just edited my last post, im using this example: https://github.com/SUSE/Portus/tree/master/examples/compose

**Comment by OBenned** [comment]
Still no luck im afraid

`portus_1    | 2017-10-31 13:20:17 +0000: SSL error, peer: 172.19.0.1, peer cert: , #<Puma::MiniSSL::SSLError: OpenSSL error: error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request - 336027804>
registry_1  | time="2017-10-31T13:20:17Z" level=error msg="retryingsink: error writing events: httpSink{http://portus:3000/v2/webhooks/events}: error posting: Post http://portus:3000/v2/webhooks/events: EOF, retrying"`

This seems to be related to its setup to run with SSL

**Comment by Vad1mo** [comment]
alright its TLS enabled then try `https://portus:3000/v2/webhooks/events`

**Comment by OBenned** [comment]
Tried that also, but that can't work either since im using a valid certificate, so the registry refuses to use that

`registry_1  | time="2017-10-31T13:25:23Z" level=error msg="retryingsink: error writing events: httpSink{https://portus:3000/v2/webhooks/events}: error posting: Post https://portus:3000/v2/webhooks/events: x509: certificate is valid for *.flexgateway.io, flexgateway.io, not portus, retrying"`

**Comment by zot24** [comment]
Just want to add that I'm experiencing the same issue as @OBenned if I add `https` to the notification endpoint.

```
11/5/2017 7:23:04 PMtime="2017-11-05T19:23:04.298382784Z" level=error msg="retryingsink: error writing events: httpSink{https://portus:3000/v2/webhooks/events}: error posting: Post https://portus:3000/v2/webhooks/events: x509: certificate is valid for test.zot24.com, not portus, retrying"
11/5/2017 7:23:04 PMtime="2017-11-05T19:23:04.298540384Z" level=warning msg="httpSink{https://portus:3000/v2/webhooks/events} encountered too many errors, backing off"
```

@OBenned how have you generated your certificates? I'm using Let's Encrypt to generate them using https://github.com/janeczku/rancher-letsencrypt and mounting the volume and then renaming `fullchain.pem` into `portus.crt` and `privkey.pem` into `portus.key`, not sure if our error might be relate with how those certificates are being generated and used by nginx/registry/portus.

**Comment by OBenned** [comment]
Im using a valid Wildcard, and have renamed them like @zot24 
Bu i only experienced that error when i strayed away from the original docker example and used the internal hostname for the container.
When i used the "correct" hostname, them there where routing problems, which was the first error i experienced

**Comment by zot24** [comment]
I'm still experiencing the error

```
11/5/2017 5:54:02 PMtime="2017-11-05T17:54:02.358256389Z" level=error msg="retryingsink: error writing events: httpSink{http://portus:3000/v2/webhooks/events}: error posting: Post http://portus:3000/v2/webhooks/events: EOF, retrying"
11/5/2017 5:54:02 PMtime="2017-11-05T17:54:02.358284789Z" level=warning msg="httpSink{http://portus:3000/v2/webhooks/events} encountered too many errors, backing off"
```

However it seem to be working it take a while for the event to reach Portus tho but eventually it update the namespace with the new pushed images and it's not `cronos` the one that updated the namespace as I disable it just to double check that it's the event + webhook what refresh it.

**Comment by Vad1mo** [comment]
I'll try to figure out a proper solution

**Comment by Vad1mo** [comment]
I pushed an image and it first try to pull, wich is correctly ignored.
`Event discarded because it's not relevant` as the pull isn't relevant.

However the push is correctly handled.  I am using the provided compose file.

Fyi: I switched to latest docker registry 2.6.2 as I run this in prod.

However I still don't see the result in Portus. Even if the event is accepted. 
@mssola @vitoravelino there is something fishy here. I'll investigate a bit more in the evening, to see if I can find out more.

```
registry_1    | time="2018-01-05T10:00:08Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.7.6 http.request.host="10.0.0.10.xip.io:5000" http.request.id=c3a8538e-656c-452e-8489-ae5b7daef5a7 http.request.method=GET http.request.remoteaddr="172.18.0.1:49760" http.request.uri="/v2/" http.request.useragent="docker/17.09.1-ce go/go1.8.3 git-commit/19e2cf6 kernel/4.9.49-moby os/linux arch/amd64 UpstreamClient(Docker-Client/17.09.1-ce \\(darwin\\))" instance.id=92c2d543-a8cd-4b28-a6d8-018e77240c75 version=v2.6.2 
registry_1    | 172.18.0.1 - - [05/Jan/2018:10:00:08 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/17.09.1-ce go/go1.8.3 git-commit/19e2cf6 kernel/4.9.49-moby os/linux arch/amd64 UpstreamClient(Docker-Client/17.09.1-ce \\(darwin\\))"
portus_1      | 
portus_1      | 
portus_1      | Started GET "/v2/token?account=vadim&scope=repository%3Atest%2Falpine%3Apush%2Cpull&service=10.0.0.10.xip.io%3A5000" for 172.18.0.1 at 2018-01-05 10:00:08 +0000
portus_1      | Cannot render console from 172.18.0.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
portus_1      | Processing by Api::V2::TokensController#show as JSON
portus_1      |   Parameters: {"account"=>"vadim", "scope"=>"repository:test/alpine:push,pull", "service"=>"10.0.0.10.xip.io:5000"}
portus_1      |   User Load (1.1ms)  SELECT  `users`.* FROM `users` WHERE `users`.`username` = 'vadim' LIMIT 1
portus_1      |   ApplicationToken Load (0.6ms)  SELECT `application_tokens`.* FROM `application_tokens` WHERE `application_tokens`.`user_id` = 2
portus_1      |   User Load (0.7ms)  SELECT  `users`.* FROM `users` WHERE `users`.`username` = 'vadim'  ORDER BY `users`.`id` ASC LIMIT 1
portus_1      |    (0.3ms)  BEGIN
portus_1      |   SQL (0.4ms)  UPDATE `users` SET `last_sign_in_at` = '2018-01-05 09:54:03', `current_sign_in_at` = '2018-01-05 10:00:08', `sign_in_count` = 6, `updated_at` = '2018-01-05 10:00:08' WHERE `users`.`id` = 2
portus_1      |    (4.7ms)  COMMIT
portus_1      |   Registry Load (0.2ms)  SELECT  `registries`.* FROM `registries` WHERE `registries`.`hostname` = '10.0.0.10.xip.io:5000' LIMIT 1
portus_1      | No hostname matching `10.0.0.10.xip.io:5000', testing external_hostname
portus_1      |   Registry Load (0.2ms)  SELECT  `registries`.* FROM `registries` WHERE `registries`.`external_hostname` = '10.0.0.10.xip.io:5000' LIMIT 1
portus_1      |   Namespace Load (0.3ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`registry_id` = 1 AND `namespaces`.`name` = 'test' LIMIT 1
portus_1      |   CACHE (0.0ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`registry_id` = 1 AND `namespaces`.`name` = 'test' LIMIT 1  [["registry_id", 1], ["name", "test"]]
portus_1      | [jwt_token] [claim] {:iss=>"10.0.0.10.xip.io", :sub=>"vadim", :aud=>"10.0.0.10.xip.io:5000", :iat=>1515146408, :nbf=>1515146403, :exp=>1515146708, :jti=>"hCkMbChKtkRWRZXyJodfDNZGCStL4LUj28m79UH3Px", :access=>[{:type=>"repository", :name=>"test/alpine", :actions=>["push", "pull"]}]}
portus_1      | Completed 200 OK in 128ms (Views: 0.3ms | ActiveRecord: 8.6ms)
registry_1    | time="2018-01-05T10:00:08Z" level=info msg="response completed" go.version=go1.7.6 http.request.host="10.0.0.10.xip.io:5000" http.request.id=7374f70b-6f10-4fee-b336-a57bfac7d915 http.request.method=HEAD http.request.remoteaddr="172.18.0.1:49768" http.request.uri="/v2/test/alpine/blobs/sha256:2fdfe1cd78c20d05774f0919be19bc1a3e4729bce219968e4188e7e0f1af679d" http.request.useragent="docker/17.09.1-ce go/go1.8.3 git-commit/19e2cf6 kernel/4.9.49-moby os/linux arch/amd64 UpstreamClient(Docker-Client/17.09.1-ce \\(darwin\\))" http.response.contenttype="application/octet-stream" http.response.duration=2.20302ms http.response.status=200 http.response.written=0 instance.id=92c2d543-a8cd-4b28-a6d8-018e77240c75 version=v2.6.2 
registry_1    | 172.18.0.1 - - [05/Jan/2018:10:00:08 +0000] "HEAD /v2/test/alpine/blobs/sha256:2fdfe1cd78c20d05774f0919be19bc1a3e4729bce219968e4188e7e0f1af679d HTTP/1.1" 200 0 "" "docker/17.09.1-ce go/go1.8.3 git-commit/19e2cf6 kernel/4.9.49-moby os/linux arch/amd64 UpstreamClient(Docker-Client/17.09.1-ce \\(darwin\\))"
registry_1    | time="2018-01-05T10:00:08Z" level=info msg="response completed" go.version=go1.7.6 http.request.host="10.0.0.10.xip.io:5000" http.request.id=300ffcdd-6dd2-410b-89a5-d1d38f54d48d http.request.method=HEAD http.request.remoteaddr="172.18.0.1:49772" http.request.uri="/v2/test/alpine/blobs/sha256:e21c333399e0aeedfd70e8827c9fba3f8e9b170ef8a48a29945eb7702bf6aa5f" http.request.useragent="docker/17.09.1-ce go/go1.8.3 git-commit/19e2cf6 kernel/4.9.49-moby os/linux arch/amd64 UpstreamClient(Docker-Client/17.09.1-ce \\(darwin\\))" http.response.contenttype="application/octet-stream" http.response.duration=2.993244ms http.response.status=200 http.response.written=0 instance.id=92c2d543-a8cd-4b28-a6d8-018e77240c75 version=v2.6.2 
registry_1    | 172.18.0.1 - - [05/Jan/2018:10:00:08 +0000] "HEAD /v2/test/alpine/blobs/sha256:e21c333399e0aeedfd70e8827c9fba3f8e9b170ef8a48a29945eb7702bf6aa5f HTTP/1.1" 200 0 "" "docker/17.09.1-ce go/go1.8.3 git-commit/19e2cf6 kernel/4.9.49-moby os/linux arch/amd64 UpstreamClient(Docker-Client/17.09.1-ce \\(darwin\\))"
portus_1      | 
portus_1      | 
portus_1      | Started POST "/v2/webhooks/events" for 172.18.0.1 at 2018-01-05 10:00:08 +0000
portus_1      | Cannot render console from 172.18.0.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
registry_1    | time="2018-01-05T10:00:09Z" level=info msg="response completed" go.version=go1.7.6 http.request.contenttype="application/vnd.docker.distribution.manifest.v2+json" http.request.host="10.0.0.10.xip.io:5000" http.request.id=3bb1b1ad-609f-4e81-855a-d5660e6ed422 http.request.method=PUT http.request.remoteaddr="172.18.0.1:49780" http.request.uri="/v2/test/alpine/manifests/latest" http.request.useragent="docker/17.09.1-ce go/go1.8.3 git-commit/19e2cf6 kernel/4.9.49-moby os/linux arch/amd64 UpstreamClient(Docker-Client/17.09.1-ce \\(darwin\\))" http.response.duration=45.978404ms http.response.status=201 http.response.written=0 instance.id=92c2d543-a8cd-4b28-a6d8-018e77240c75 version=v2.6.2 
registry_1    | 172.18.0.1 - - [05/Jan/2018:10:00:08 +0000] "PUT /v2/test/alpine/manifests/latest HTTP/1.1" 201 0 "" "docker/17.09.1-ce go/go1.8.3 git-commit/19e2cf6 kernel/4.9.49-moby os/linux arch/amd64 UpstreamClient(Docker-Client/17.09.1-ce \\(darwin\\))"
portus_1      | Processing by Api::V2::EventsController#create as JSON
portus_1      | Filtering event:
portus_1      | {
portus_1      |   "id": "3b47f5ef-68b1-443b-b997-3908dcbd608e",
portus_1      |   "timestamp": "2018-01-05T10:00:08.948725896Z",
portus_1      |   "action": "pull",
portus_1      |   "target": {
portus_1      |     "mediaType": "application/octet-stream",
portus_1      |     "size": 2064911,
portus_1      |     "digest": "sha256:2fdfe1cd78c20d05774f0919be19bc1a3e4729bce219968e4188e7e0f1af679d",
portus_1      |     "length": 2064911,
portus_1      |     "repository": "test/alpine",
portus_1      |     "url": "http://10.0.0.10.xip.io:5000/v2/test/alpine/blobs/sha256:2fdfe1cd78c20d05774f0919be19bc1a3e4729bce219968e4188e7e0f1af679d"
portus_1      |   },
portus_1      |   "request": {
portus_1      |     "id": "7374f70b-6f10-4fee-b336-a57bfac7d915",
portus_1      |     "addr": "172.18.0.1:49768",
portus_1      |     "host": "10.0.0.10.xip.io:5000",
portus_1      |     "method": "HEAD",
portus_1      |     "useragent": "docker/17.09.1-ce go/go1.8.3 git-commit/19e2cf6 kernel/4.9.49-moby os/linux arch/amd64 UpstreamClient(Docker-Client/17.09.1-ce \\(darwin\\))"
portus_1      |   },
portus_1      |   "actor": {
portus_1      |     "name": "vadim"
portus_1      |   },
portus_1      |   "source": {
portus_1      |     "addr": "f80aebb7d5bc:5000",
portus_1      |     "instanceID": "92c2d543-a8cd-4b28-a6d8-018e77240c75"
portus_1      |   }
portus_1      | }
portus_1      | Unsupported mediaType 'application/octet-stream'
portus_1      | Event discarded because it's not relevant
portus_1      | Completed 202 Accepted in 1ms (ActiveRecord: 0.0ms)
portus_1      | 
portus_1      | 
portus_1      | Started POST "/v2/webhooks/events" for 172.18.0.1 at 2018-01-05 10:00:09 +0000
portus_1      | Cannot render console from 172.18.0.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
portus_1      | Processing by Api::V2::EventsController#create as JSON
portus_1      | Filtering event:
portus_1      | {
portus_1      |   "id": "ad14684e-6aed-4fe2-8af0-8b9fdefe8249",
portus_1      |   "timestamp": "2018-01-05T10:00:08.964083946Z",
portus_1      |   "action": "pull",
portus_1      |   "target": {
portus_1      |     "mediaType": "application/octet-stream",
portus_1      |     "size": 1511,
portus_1      |     "digest": "sha256:e21c333399e0aeedfd70e8827c9fba3f8e9b170ef8a48a29945eb7702bf6aa5f",
portus_1      |     "length": 1511,
portus_1      |     "repository": "test/alpine",
portus_1      |     "url": "http://10.0.0.10.xip.io:5000/v2/test/alpine/blobs/sha256:e21c333399e0aeedfd70e8827c9fba3f8e9b170ef8a48a29945eb7702bf6aa5f"
portus_1      |   },
portus_1      |   "request": {
portus_1      |     "id": "300ffcdd-6dd2-410b-89a5-d1d38f54d48d",
portus_1      |     "addr": "172.18.0.1:49772",
portus_1      |     "host": "10.0.0.10.xip.io:5000",
portus_1      |     "method": "HEAD",
portus_1      |     "useragent": "docker/17.09.1-ce go/go1.8.3 git-commit/19e2cf6 kernel/4.9.49-moby os/linux arch/amd64 UpstreamClient(Docker-Client/17.09.1-ce \\(darwin\\))"
portus_1      |   },
portus_1      |   "actor": {
portus_1      |     "name": "vadim"
portus_1      |   },
portus_1      |   "source": {
portus_1      |     "addr": "f80aebb7d5bc:5000",
portus_1      |     "instanceID": "92c2d543-a8cd-4b28-a6d8-018e77240c75"
portus_1      |   }
portus_1      | }
portus_1      | Unsupported mediaType 'application/octet-stream'
portus_1      | Event discarded because it's not relevant
portus_1      | Completed 202 Accepted in 1ms (ActiveRecord: 0.0ms)
portus_1      | 
portus_1      | 
portus_1      | Started POST "/v2/webhooks/events" for 172.18.0.1 at 2018-01-05 10:00:09 +0000
portus_1      | Cannot render console from 172.18.0.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
portus_1      | Processing by Api::V2::EventsController#create as JSON
portus_1      | Filtering event:
portus_1      | {
portus_1      |   "id": "3a7d853e-99bd-412b-80ac-9e69559e85c8",
portus_1      |   "timestamp": "2018-01-05T10:00:09.014752039Z",
portus_1      |   "action": "push",
portus_1      |   "target": {
portus_1      |     "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
portus_1      |     "size": 528,
portus_1      |     "digest": "sha256:5cb04fce748f576d7b72a37850641de8bd725365519673c643ef2d14819b42c6",
portus_1      |     "length": 528,
portus_1      |     "repository": "test/alpine",
portus_1      |     "url": "http://10.0.0.10.xip.io:5000/v2/test/alpine/manifests/sha256:5cb04fce748f576d7b72a37850641de8bd725365519673c643ef2d14819b42c6",
portus_1      |     "tag": "latest"
portus_1      |   },
portus_1      |   "request": {
portus_1      |     "id": "3bb1b1ad-609f-4e81-855a-d5660e6ed422",
portus_1      |     "addr": "172.18.0.1:49780",
portus_1      |     "host": "10.0.0.10.xip.io:5000",
portus_1      |     "method": "PUT",
portus_1      |     "useragent": "docker/17.09.1-ce go/go1.8.3 git-commit/19e2cf6 kernel/4.9.49-moby os/linux arch/amd64 UpstreamClient(Docker-Client/17.09.1-ce \\(darwin\\))"
portus_1      |   },
portus_1      |   "actor": {
portus_1      |     "name": "vadim"
portus_1      |   },
portus_1      |   "source": {
portus_1      |     "addr": "f80aebb7d5bc:5000",
portus_1      |     "instanceID": "92c2d543-a8cd-4b28-a6d8-018e77240c75"
portus_1      |   }
portus_1      | }
portus_1      |   RegistryEvent Exists (0.5ms)  SELECT  1 AS one FROM `registry_events` WHERE `registry_events`.`event_id` = '3a7d853e-99bd-412b-80ac-9e69559e85c8' LIMIT 1
portus_1      |    (0.3ms)  BEGIN
portus_1      |   SQL (1.3ms)  INSERT INTO `registry_events` (`event_id`, `data`, `status`, `created_at`, `updated_at`) VALUES ('3a7d853e-99bd-412b-80ac-9e69559e85c8', '{\"id\":\"3a7d853e-99bd-412b-80ac-9e69559e85c8\",\"timestamp\":\"2018-01-05T10:00:09.014752039Z\",\"action\":\"push\",\"target\":{\"mediaType\":\"application/vnd.docker.distribution.manifest.v2+json\",\"size\":528,\"digest\":\"sha256:5cb04fce748f576d7b72a37850641de8bd725365519673c643ef2d14819b42c6\",\"length\":528,\"repository\":\"test/alpine\",\"url\":\"http://10.0.0.10.xip.io:5000/v2/test/alpine/manifests/sha256:5cb04fce748f576d7b72a37850641de8bd725365519673c643ef2d14819b42c6\",\"tag\":\"latest\"},\"request\":{\"id\":\"3bb1b1ad-609f-4e81-855a-d5660e6ed422\",\"addr\":\"172.18.0.1:49780\",\"host\":\"10.0.0.10.xip.io:5000\",\"method\":\"PUT\",\"useragent\":\"docker/17.09.1-ce go/go1.8.3 git-commit/19e2cf6 kernel/4.9.49-moby os/linux arch/amd64 UpstreamClient(Docker-Client/17.09.1-ce \\\\(darwin\\\\))\"},\"actor\":{\"name\":\"vadim\"},\"source\":{\"addr\":\"f80aebb7d5bc:5000\",\"instanceID\":\"92c2d543-a8cd-4b28-a6d8-018e77240c75\"}}', 2, '2018-01-05 10:00:10', '2018-01-05 10:00:10')
portus_1      |    (4.0ms)  COMMIT
portus_1      | Completed 202 Accepted in 132ms (ActiveRecord: 7.8ms)

```

**Comment by Vad1mo** [comment]
I dig into this topic a bit and and it seems to be related with the new backgroud worker changes.  

It seems that the events that come in are stored in the DB and the background worker is processing them. However if I look at the compose file I see that the background Worker is only triggered once at its start producing the error `bin/rails: end of file reached (EOFError)` related to #1561

Questions to @mssola and @vitoravelino:

1. Should the background container run periodically as a separate process?
 
2. Should  #1561 fix the `bin/rails: end of file reached (EOFError)` error if so then it doesn't I am running the master with merged #1561.

**Comment by vitoravelino** [comment]
> Should #1561 fix the bin/rails: end of file reached (EOFError) error if so then it doesn't I am running the master with merged #1561.

#1561 was supposed to fix the EOF error in the `sync.rb` file by ignoring it and not breaking the container. It doesn't solve the error to happen. The EOF error reported here was way before the background container strategy were implemented.

**Comment by Itadmin-corner** [comment]
This error persists. my wildcard SSL is not working. I ensured that containers internally go to correct container. I have tried everything mentioned above. can you please suggest on this?
