### ISSUE TITLE
ActionView::Template::Error (File to import not found or unreadable: raleway.

### ISSUE THREAD

**Issue by dober** [SUSE/Portus#1574]
Trying to run https://github.com/SUSE/Portus/blob/master/examples/compose/docker-compose.yml
But there is something wrong in image: opensuse/portus:head

```
Database ready
[38] Puma starting in cluster mode...
[38] * Version 2.16.0 (ruby 2.1.9-p490), codename: Midwinter Nights Trance
[38] * Min threads: 1, max threads: 4
[38] * Environment: production
[38] * Process workers: 2
[38] * Preloading application
[Mailer config] Host:     portus.test.lan
[Mailer config] Protocol: https://
[38] * Listening on ssl://0.0.0.0:3000?cert=/etc/letsencrypt/live/registry.registry.tld/fullchain.pem&key=/etc/letsencrypt/live/registry.registry.tld/privkey.pem
[38] Use Ctrl-C to stop
[38] - Worker 0 (pid: 41) booted, phase: 0
[38] - Worker 1 (pid: 49) booted, phase: 0
Started GET "/users/sign_up" for 5.39.95.84 at 2018-01-07 03:18:06 +0000
Processing by Auth::RegistrationsController#new as HTML
  Rendered shared/_notification.html.slim (28.4ms)
  Rendered shared/_notification.html.slim (0.1ms)
  Rendered shared/_notifications.html.slim (49.6ms)
  Rendered devise/registrations/new.html.slim within layouts/authentication (139.7ms)
Completed 500 Internal Server Error in 851ms (ActiveRecord: 6.2ms)

ActionView::Template::Error` (File to import not found or unreadable: raleway.
Load paths:
  /srv/Portus/app/assets/images
  /srv/Portus/app/assets/javascripts
  /srv/Portus/app/assets/stylesheets
  /srv/Portus/vendor/bundle/ruby/2.1.0/gems/font-awesome-rails-4.4.0.0/app/assets/fonts
  /srv/Portus/vendor/bundle/ruby/2.1.0/gems/font-awesome-rails-4.4.0.0/app/assets/stylesheets
  /srv/Portus/vendor/bundle/ruby/2.1.0/gems/bootstrap-sass-3.3.5/assets/stylesheets
  /srv/Portus/vendor/bundle/ruby/2.1.0/gems/bootstrap-sass-3.3.5/assets/javascripts
  /srv/Portus/vendor/bundle/ruby/2.1.0/gems/bootstrap-sass-3.3.5/assets/fonts
  /srv/Portus/vendor/bundle/ruby/2.1.0/gems/bootstrap-sass-3.3.5/assets/images
  /srv/Portus/vendor/bundle/ruby/2.1.0/gems/bootstrap-sass-3.3.5/assets/stylesheets
  (in /srv/Portus/app/assets/stylesheets/application.scss:3)):
    2: html
    3:   head
    4:     title Portus
    5:     = stylesheet_link_tag 'application', media: 'all'
    6:     = javascript_include_tag(*webpack_asset_paths("application"))
    7:     = csrf_meta_tags
    8:     meta content="width=device-width, initial-scale=1" name="viewport"
  app/assets/stylesheets/application.scss:3
  app/views/layouts/authentication.html.slim:5:in `_app_views_layouts_authentication_html_slim___1452995626520381450_52051400'
  app/controllers/auth/registrations_controller.rb:16:in `new'
Processing by ErrorsController#show as HTML
  Parameters: {"status"=>"500"}
  Rendered errors/500.html.erb within layouts/errors (1.7ms)
Completed 500 Internal Server Error in 206ms (ActiveRecord: 0.0ms)
Error during failsafe response: File to import not found or unreadable: raleway.
Load paths:
  /srv/Portus/app/assets/images
  /srv/Portus/app/assets/javascripts
  /srv/Portus/app/assets/stylesheets
  /srv/Portus/vendor/bundle/ruby/2.1.0/gems/font-awesome-rails-4.4.0.0/app/assets/fonts
  /srv/Portus/vendor/bundle/ruby/2.1.0/gems/font-awesome-rails-4.4.0.0/app/assets/stylesheets
  /srv/Portus/vendor/bundle/ruby/2.1.0/gems/bootstrap-sass-3.3.5/assets/stylesheets
  /srv/Portus/vendor/bundle/ruby/2.1.0/gems/bootstrap-sass-3.3.5/assets/javascripts
  /srv/Portus/vendor/bundle/ruby/2.1.0/gems/bootstrap-sass-3.3.5/assets/fonts
  /srv/Portus/vendor/bundle/ruby/2.1.0/gems/bootstrap-sass-3.3.5/assets/images
  /srv/Portus/vendor/bundle/ruby/2.1.0/gems/bootstrap-sass-3.3.5/assets/stylesheets
  (in /srv/Portus/app/assets/stylesheets/application.scss:3)
  /srv/Portus/app/assets/stylesheets/application.scss:3
```

Plus i have same issue [https://github.com/SUSE/Portus/issues/1573](url)

**Comment by Vesli** [comment]
I've got almost the same as well:

> Error during failsafe response: File to import not found or unreadable: raleway.

**Comment by mssola** [comment]
I'm sure this is a side-effect of #1418. I'll mark it as a duplicate and re-visit this once I've finally fixed that.

Meanwhile, you might want to use the image that you can build from the Dockerfile provided on the root of the project.

Thanks for reporting 👍

**Comment by mssola** [comment]
Fixed. See #1418.

**Comment by ju2wheels** [comment]
@mssola Im still getting the raleway error on the latest opensuse/portus:head . Have the images been rebuilt to include the fix?

**Comment by mssola** [comment]
@ju2wheels I just removed the `opensuse/portus:head` image I had locally and pulled again to be sure, and I cannot reproduce this issue. Are you sure you are using the latest image ?

**Comment by ju2wheels** [comment]
Yep, Im sure im on the latest. I deleted all my local images just to be sure.

```
portus_1      | Database ready
portus_1      | [73] Puma starting in cluster mode...
portus_1      | [73] * Version 3.10.0 (ruby 2.5.0-p0), codename: Russell's Teapot
portus_1      | [73] * Min threads: 1, max threads: 4
portus_1      | [73] * Environment: production
portus_1      | [73] * Process workers: 2
portus_1      | [73] * Preloading application
portus_1      | [Mailer config] Host:     repository-manager.mycompany.com
portus_1      | [Mailer config] Protocol: https://
portus_1      | [73] * Listening on ssl://0.0.0.0:3000?cert=/certificates/portus.crt&key=/certificates/portus.key&verify_mode=none
portus_1      | [73] Use Ctrl-C to stop
portus_1      | [73] - Worker 0 (pid: 76) booted, phase: 0
portus_1      | [73] - Worker 1 (pid: 81) booted, phase: 0
portus_1      | Started GET "/" for 172.18.0.6 at 2018-02-21 16:56:58 +0000
portus_1      | Processing by Auth::SessionsController#new as HTML
portus_1      |   Rendered shared/_notification.html.slim (4.9ms)
portus_1      |   Rendered shared/_notifications.html.slim (9.3ms)
portus_1      |   Rendered devise/sessions/new.html.slim within layouts/authentication (571.0ms)
portus_1      | Completed 401 Unauthorized in 600ms (ActiveRecord: 1.6ms)
portus_1      | 
portus_1      | ActionView::Template::Error (File to import not found or unreadable: raleway.
portus_1      | Load paths:
portus_1      |   /srv/Portus/app/assets/images
portus_1      |   /srv/Portus/app/assets/javascripts
portus_1      |   /srv/Portus/app/assets/stylesheets
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/font-awesome-rails-4.7.0.3/app/assets/fonts
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/font-awesome-rails-4.7.0.3/app/assets/stylesheets
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/bootstrap-sass-3.3.7/assets/stylesheets
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/bootstrap-sass-3.3.7/assets/javascripts
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/bootstrap-sass-3.3.7/assets/fonts
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/bootstrap-sass-3.3.7/assets/images
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/bootstrap-sass-3.3.7/assets/stylesheets):
portus_1      |     3:     .col-md-4.col-sm-2.col-xs-1
portus_1      |     4:     .col-md-4.col-sm-8.col-xs-10.text-center
portus_1      |     5:       = render 'shared/notifications'
portus_1      |     6:       = image_tag 'layout/portus-logo-login-page.png', class: 'login-picture'
portus_1      |     7:       = form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
portus_1      |     8:         - if Portus::LDAP.enabled? || APP_CONFIG.enabled?("oauth.local_login")
portus_1      |     9:           = f.text_field :username, class: 'input form-control input-lg first', placeholder: 'Username', autofocus: true, required: true
portus_1      |   app/assets/stylesheets/application.scss:3
portus_1      |   app/views/devise/sessions/new.html.slim:6:in `_app_views_devise_sessions_new_html_slim__110884667054085130_70043804189220'
portus_1      |   app/controllers/auth/sessions_controller.rb:16:in `new'
portus_1      |   app/middleware/catch_json_parse_errors.rb:11:in `call'
portus_1      | 
portus_1      | 
portus_1      | Processing by ErrorsController#show as HTML
portus_1      |   Parameters: {"status"=>"500"}
portus_1      |   Rendered errors/500.html.erb within layouts/errors (0.9ms)
portus_1      | Completed 401 Unauthorized in 168ms (ActiveRecord: 0.0ms)
portus_1      | Error during failsafe response: File to import not found or unreadable: raleway.
portus_1      | Load paths:
portus_1      |   /srv/Portus/app/assets/images
portus_1      |   /srv/Portus/app/assets/javascripts
portus_1      |   /srv/Portus/app/assets/stylesheets
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/font-awesome-rails-4.7.0.3/app/assets/fonts
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/font-awesome-rails-4.7.0.3/app/assets/stylesheets
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/bootstrap-sass-3.3.7/assets/stylesheets
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/bootstrap-sass-3.3.7/assets/javascripts
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/bootstrap-sass-3.3.7/assets/fonts
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/bootstrap-sass-3.3.7/assets/images
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/bootstrap-sass-3.3.7/assets/stylesheets
portus_1      |   /srv/Portus/app/assets/stylesheets/application.scss:3
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/import_node.rb:67:in `rescue in import'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/import_node.rb:44:in `import'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/import_node.rb:28:in `imported_file'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/import_node.rb:37:in `css_import?'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:314:in `visit_import'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/visitors/base.rb:36:in `visit'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:162:in `block in visit'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/stack.rb:79:in `block in with_base'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/stack.rb:115:in `with_frame'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/stack.rb:79:in `with_base'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:162:in `visit'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/visitors/base.rb:52:in `map'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/visitors/base.rb:52:in `visit_children'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:171:in `block in visit_children'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:183:in `with_environment'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:170:in `visit_children'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/visitors/base.rb:36:in `block in visit'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:190:in `visit_root'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/visitors/base.rb:36:in `visit'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:161:in `visit'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:10:in `visit'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/root_node.rb:36:in `css_tree'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/root_node.rb:20:in `render'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/engine.rb:284:in `render'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-rails-5.0.7/lib/sass/rails/template.rb:47:in `evaluate'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/tilt-2.0.8/lib/tilt/template.rb:109:in `render'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/legacy_tilt_processor.rb:25:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:23:in `block in call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/utils.rb:200:in `dfs'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:24:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:92:in `[]'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:355:in `find_asset'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:336:in `digest_path'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:325:in `asset_path'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:102:in `block in resolve_asset_path'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:242:in `block in resolve_asset'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:241:in `each'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:241:in `detect'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:241:in `resolve_asset'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:101:in `resolve_asset_path'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:79:in `compute_asset_path'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/helpers/asset_url_helper.rb:135:in `asset_path'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/helpers/asset_url_helper.rb:267:in `stylesheet_path'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/helpers/asset_tag_helper.rb:100:in `block in stylesheet_link_tag'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/helpers/asset_tag_helper.rb:96:in `map'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/helpers/asset_tag_helper.rb:96:in `stylesheet_link_tag'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:185:in `block in stylesheet_link_tag'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:183:in `map'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:183:in `stylesheet_link_tag'
portus_1      |   /srv/Portus/app/views/layouts/errors.html.slim:5:in `_app_views_layouts_errors_html_slim__1357017584960853834_70043819777020'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/template.rb:145:in `block in render'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/notifications.rb:166:in `instrument'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/template.rb:333:in `instrument'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/template.rb:143:in `render'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/renderer/template_renderer.rb:14:in `render'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/renderer/renderer.rb:46:in `render_template'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/renderer/renderer.rb:27:in `render'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/rendering.rb:100:in `_render_template'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/streaming.rb:217:in `_render_template'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/rendering.rb:83:in `render_to_body'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/abstract_controller/rendering.rb:25:in `render'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/rendering.rb:16:in `render'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
portus_1      |   /usr/lib64/ruby/2.5.0/benchmark.rb:308:in `realtime'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/core_ext/benchmark.rb:12:in `ms'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/instrumentation.rb:43:in `render'
portus_1      |   /srv/Portus/app/controllers/errors_controller.rb:17:in `show'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/abstract_controller/base.rb:198:in `process_action'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/rendering.rb:10:in `process_action'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:117:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:505:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:81:in `run_callbacks'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/abstract_controller/callbacks.rb:19:in `process_action'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/rescue.rb:29:in `process_action'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/notifications.rb:164:in `block in instrument'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/notifications.rb:164:in `instrument'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/abstract_controller/base.rb:137:in `process'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/rendering.rb:30:in `process'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal.rb:196:in `dispatch'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal.rb:237:in `block in action'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:43:in `serve'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/journey/router.rb:43:in `block in serve'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/journey/router.rb:30:in `each'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/journey/router.rb:30:in `serve'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:817:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/show_exceptions.rb:47:in `render_exception'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/show_exceptions.rb:35:in `rescue in call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/show_exceptions.rb:29:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:38:in `call_app'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `block in call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `block in tagged'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:26:in `tagged'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `tagged'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/request_id.rb:21:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:518:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:165:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:66:in `block in call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `each'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
nginx_1       | 172.30.117.199 - - [21/Feb/2018:16:57:00 +0000] "GET / HTTP/2.0" 500 182 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36"
portus_1      | Started GET "/favicon.ico" for 172.18.0.6 at 2018-02-21 16:57:00 +0000
portus_1      | 
portus_1      | ActionController::RoutingError (No route matches [GET] "/favicon.ico"):
portus_1      |   vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
portus_1      |   vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
portus_1      |   vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:38:in `call_app'
portus_1      |   vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `block in call'
portus_1      |   vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `block in tagged'
portus_1      |   vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:26:in `tagged'
portus_1      |   vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `tagged'
portus_1      |   vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `call'
portus_1      |   vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/request_id.rb:21:in `call'
portus_1      |   vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
portus_1      |   vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
portus_1      |   vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
portus_1      |   vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
portus_1      |   vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:518:in `call'
portus_1      |   vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:165:in `call'
portus_1      |   vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:66:in `block in call'
portus_1      |   vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `each'
portus_1      |   vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `call'
portus_1      |   vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
portus_1      |   vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
portus_1      |   vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
portus_1      |   vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
portus_1      |   vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
portus_1      | 
portus_1      | 
portus_1      | Processing by ErrorsController#show as HTML
portus_1      |   Parameters: {"status"=>"404"}
portus_1      |   Rendered errors/404.html.slim within layouts/errors (2.8ms)
portus_1      | Error during failsafe response: File to import not found or unreadable: raleway.
portus_1      | Load paths:
portus_1      |   /srv/Portus/app/assets/images
portus_1      |   /srv/Portus/app/assets/javascripts
portus_1      |   /srv/Portus/app/assets/stylesheets
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/font-awesome-rails-4.7.0.3/app/assets/fonts
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/font-awesome-rails-4.7.0.3/app/assets/stylesheets
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/bootstrap-sass-3.3.7/assets/stylesheets
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/bootstrap-sass-3.3.7/assets/javascripts
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/bootstrap-sass-3.3.7/assets/fonts
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/bootstrap-sass-3.3.7/assets/images
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/bootstrap-sass-3.3.7/assets/stylesheets
portus_1      |   /srv/Portus/app/assets/stylesheets/application.scss:3
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/import_node.rb:67:in `rescue in import'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/import_node.rb:44:in `import'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/import_node.rb:28:in `imported_file'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/import_node.rb:37:in `css_import?'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:314:in `visit_import'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/visitors/base.rb:36:in `visit'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:162:in `block in visit'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/stack.rb:79:in `block in with_base'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/stack.rb:115:in `with_frame'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/stack.rb:79:in `with_base'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:162:in `visit'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/visitors/base.rb:52:in `map'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/visitors/base.rb:52:in `visit_children'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:171:in `block in visit_children'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:183:in `with_environment'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:170:in `visit_children'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/visitors/base.rb:36:in `block in visit'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:190:in `visit_root'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/visitors/base.rb:36:in `visit'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:161:in `visit'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:10:in `visit'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/root_node.rb:36:in `css_tree'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/tree/root_node.rb:20:in `render'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-3.4.25/lib/sass/engine.rb:284:in `render'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sass-rails-5.0.7/lib/sass/rails/template.rb:47:in `evaluate'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/tilt-2.0.8/lib/tilt/template.rb:109:in `render'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/legacy_tilt_processor.rb:25:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:23:in `block in call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/utils.rb:200:in `dfs'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:24:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:92:in `[]'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:355:in `find_asset'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:336:in `digest_path'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:325:in `asset_path'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:102:in `block in resolve_asset_path'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:242:in `block in resolve_asset'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:241:in `each'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:241:in `detect'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:241:in `resolve_asset'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:101:in `resolve_asset_path'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:79:in `compute_asset_path'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/helpers/asset_url_helper.rb:135:in `asset_path'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/helpers/asset_url_helper.rb:267:in `stylesheet_path'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/helpers/asset_tag_helper.rb:100:in `block in stylesheet_link_tag'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/helpers/asset_tag_helper.rb:96:in `map'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/helpers/asset_tag_helper.rb:96:in `stylesheet_link_tag'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:185:in `block in stylesheet_link_tag'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:183:in `map'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:183:in `stylesheet_link_tag'
portus_1      |   /srv/Portus/app/views/layouts/errors.html.slim:5:in `_app_views_layouts_errors_html_slim__1357017584960853834_70043819777020'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/template.rb:145:in `block in render'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/notifications.rb:166:in `instrument'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/template.rb:333:in `instrument'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/template.rb:143:in `render'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/renderer/template_renderer.rb:14:in `render'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/renderer/renderer.rb:46:in `render_template'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/renderer/renderer.rb:27:in `render'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/rendering.rb:100:in `_render_template'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/streaming.rb:217:in `_render_template'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/rendering.rb:83:in `render_to_body'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/abstract_controller/rendering.rb:25:in `render'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/rendering.rb:16:in `render'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
portus_1      |   /usr/lib64/ruby/2.5.0/benchmark.rb:308:in `realtime'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/core_ext/benchmark.rb:12:in `ms'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/instrumentation.rb:43:in `render'
portus_1      |   /srv/Portus/app/controllers/errors_controller.rb:17:in `show'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/abstract_controller/base.rb:198:in `process_action'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/rendering.rb:10:in `process_action'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:117:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:505:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:81:in `run_callbacks'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/abstract_controller/callbacks.rb:19:in `process_action'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/rescue.rb:29:in `process_action'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/notifications.rb:164:in `block in instrument'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/notifications.rb:164:in `instrument'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/abstract_controller/base.rb:137:in `process'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/rendering.rb:30:in `process'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal.rb:196:in `dispatch'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal.rb:237:in `block in action'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:43:in `serve'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/journey/router.rb:43:in `block in serve'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/journey/router.rb:30:in `each'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/journey/router.rb:30:in `serve'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:817:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/show_exceptions.rb:47:in `render_exception'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/show_exceptions.rb:35:in `rescue in call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/show_exceptions.rb:29:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:38:in `call_app'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `block in call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `block in tagged'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:26:in `tagged'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `tagged'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/request_id.rb:21:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:518:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:165:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:66:in `block in call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `each'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
portus_1      |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
portus_1      | Completed 401 Unauthorized in 116ms (ActiveRecord: 0.0ms)
nginx_1       | 172.30.117.199 - - [21/Feb/2018:16:57:02 +0000] "GET /favicon.ico HTTP/2.0" 500 182 "https://repository-manager.mycompany.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36"
```

Im almost pretty sure I am also have issues with the SSL cert though I dont know if that would cause these particular errors.
