### ISSUE TITLE
LDAP: fix the current situation between username and ldap_name

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#736]
Right now what we have is that for LDAP, created users will have the proper LDAP username in the `ldap_name`, and the stripped one in `username`. This leads to the situation in which `username` means a different thing between non-LDAP and LDAP. Bugs have appeared because of this (the last one being #732).

## Proposal

- `username` always contains the original user name.
- `namespace` will contain the personal namespace associated to the user.

This way, whenever we want to show the user name, we just call `username` (we don't have to guard it with `if LDAP.enabled?` all the time). This would also fix some quirks on the UI (e.g. listing users by their modified names on LDAP). Moreover, this gives us more flexibility if in the future we want to support other authentication protocols (e.g. SAML as described in #597).

## Drawback

This has one major drawback: we would have to provide a task to migrate from the current scenario to this new one. This is not *such* a big problem because we need to provide a way to migrate from 2.0 to the future 2.1 anyways (it already happened when we released 2.0 that people asked on how to upgrade from version 1.0.1, and we didn't have a proper way :/).

## Alternatives

We could also provide a method in the `User` model called `name`, that did the trick of returning `ldap_name` instead of `username` when needed. This also has some downsides:

- We would not only have to replace all the `username` and `ldap_name` usages, but we would also have to remember to use this method instead of the attributes from now on.
- We would have to replace all the `find_by` calls to something that can play with the new `name` method.

## Tasks

- [x] Implement change.
- [x] Make sure that issue #732 is fixed.
- [x] Implement rake task.
- [ ] Update documentation.

~~This issues **supersedes** #699.~~

**Comment by lonewulf** [comment]
Hi,

The User model being changed for this issue, wouldn't it be a good time to add a display name to it, as mentioned in #699 ?

Regards,

**Comment by mssola** [comment]
@lonewulf that issue should be fixed by this one. As I said:

     This would also fix some quirks on the UI

I'll add the issue on my original comment. Thanks for the reference :)

**Comment by lonewulf** [comment]
Fixes some quirks yes, but usernames are not always user-friendly, you're still not able to guess who's behind a given username, and it feels problematic if you need to cross-check with your directory to find who is behind. That's what I meant behind the idea of display name.

Regards,

**Comment by mssola** [comment]
The idea is that now the "display name" will be the original LDAP name. So, if your LDAP name is "first.second", then this will be the one being shown as your username in all places of the UI (and not `firstsecond`, which is the current behavior).

Do you mean that you want to see another name besides the original one ?

**Comment by lonewulf** [comment]
> Do you mean that you want to see another name besides the original one ?

Yup, that's what I meant, sometimes usernames are totally unrelated to the real names. Let's say something along user12345 and user98765.
I had in mind to use the display name to show the user real name (That could be pulled from the LDAP server when the user is created), as it's more user-friendly.

**Comment by mssola** [comment]
@lonewulf fair enough. I've re-opened #699.
