### ISSUE TITLE
newly successfully pushed images still not appear in Recent activities feeds.

### ISSUE THREAD

**Issue by nancykyo** [SUSE/Portus#878]
#version: Portus-2.0.1
also could not find error msg in log/production.log
![image](https://cloud.githubusercontent.com/assets/1332885/15279522/cc1c1b74-1b57-11e6-875f-187b003f29ba.png)
![image](https://cloud.githubusercontent.com/assets/1332885/15279577/68ad343c-1b58-11e6-8d2d-056c6d01743c.png)

here is the log before, this seems to be the normal behavior.
![image](https://cloud.githubusercontent.com/assets/1332885/15279465/3a8cae62-1b57-11e6-83ec-b8c4cd57d647.png)

how can I debug this to find out what's wrong?

**Comment by nancykyo** [comment]
the portus interface return 301
![image](https://cloud.githubusercontent.com/assets/1332885/15281725/5c938774-1b70-11e6-9979-dc53545cba05.png)

**Comment by nancykyo** [comment]
updates:
after I sync manually, the images can be searched.
but newly pushed images still not appear in **Recent activities** feeds.
![image](https://cloud.githubusercontent.com/assets/1332885/15282922/298d2c8c-1b79-11e6-8bb2-0a0afc75b93a.png)

**Comment by mssola** [comment]
Which version of Docker are you using, and which version of docker distribution ? As stated in the [README](https://github.com/SUSE/Portus#supported-versions) file, not all versions are supported in 2.0.1. Maybe you should be considering updating to 2.0.4 ?

**Comment by boyand** [comment]
I have the same problem and I am using Docker 1.9.1, Portus 2.0.5, Registry 2.4.0

**Comment by mssola** [comment]
@boyand could you provide more information on this ? I'm asking because this is one of those issues that are really hard to debug because there are a lot of factors that can trigger this issue, and it may very well be a problem in your current setup (not a bug in Portus itself).

**Comment by jovandeginste** [comment]
I did some more debugging and in the (current, 8532207a390d2ddb73cff59cf6385e31cab63210) code, after changing this I saw every (new) push to an existing tag in the activity feed:

```diff
diff --git a/app/models/repository.rb b/app/models/repository.rb
index 0491214..057bc35 100644
--- a/app/models/repository.rb
+++ b/app/models/repository.rb
@@ -142,7 +142,13 @@ class Repository < ActiveRecord::Base
     elsif repository.tags.exists?(name: tag)
       # Update digest if the given tag already exists.
       _, digest = Repository.id_and_digest_from_event(event, repository.full_name)
-      repository.tags.find_by(name: tag).update!(digest: digest)
+      repository_tag = repository.tags.find_by(name: tag)
+      if repository_tag.digest == digest
+        return
+      end
+
+      repository_tag.update!(digest: digest)
+      repository.create_activity(:push, owner: actor, recipient: repository_tag)
       return
     end
```

**Comment by mssola** [comment]
This should've been fixed by #1031. If not, feel free to re-open.

**Comment by vagharsh** [comment]
hey guys ,the case is closed but the problem still exists with me .. i am using docker 1.12.6 , i deployed the development way in docker containers and pushed after all the successful configurations i assume ., i was able to push and pull the image to and from the registry , but i can not see the pushed images on the portus dashboard.
