### ISSUE TITLE
Is there an easy installation guide for CentOS7?

### ISSUE THREAD

**Issue by najeebdanish** [SUSE/Portus#982]
Is there an easy installation guide for CentOS7? If I follow the instructions on the Portus documentation page it seems pretty cumber some.

**Comment by najeebdanish** [comment]
I am trying to install Portus on CentOS7 with Docker registry running on the same machine.

**Comment by mssola** [comment]
No worries, let's see. First of all, we recommend to go through [this newcomers page](http://port.us.org/docs/first-steps.html) to everyone that might not be familiar with Portus and how it interacts with an on-premise Docker registry. Moreover, following the "Quick Start" section as described [here](http://port.us.org/documentation.html) might also be useful to you.

Now, in your case, I see multiple options to proceed:

1. Using the RPM as described [here](http://port.us.org/docs/setups/1_rpm_packages.html). I wouldn't recommend this option because we've only tested it in openSUSE, so it's not guaranteed to work on Fedora/CentOS/RH. That being said, it might work.
2. Using Docker images. If you only want to try out Portus, there's the [development image](https://github.com/SUSE/Portus/wiki/Docker-Compose-Environment) for it. Otherwise, you might want to use [our production-ready image](https://hub.docker.com/r/opensuse/portus/). We are working on documentation for it, but you could in principle just use this image in a docker-compose setup.

You might also want to read documentation pages like [this one](http://port.us.org/docs/Configuring-Portus.html) and [this other one](http://port.us.org/docs/How-to-setup-secure-registry.html) that deal with configuration.

**Comment by Djelibeybi** [comment]
I documented how to do this on Oracle Linux 7 with sample configuration files over in a personal repo: https://github.com/Djelibeybi/Portus-On-OracleLinux7

This should work on CentOS 7 as well.

**Comment by mssola** [comment]
@Djelibeybi thanks! :clap:

**Comment by Djelibeybi** [comment]
@mssola you're welcome. If you have any issues, feel free to open an issue over on my repo.

**Comment by It4lik** [comment]
Hi, 

I am using Portus in the following environment : 
A **single CentOS 7 machine** with :
-   Apache reverse proxy (provides security (especially encryption)
-   Unicorn app server (serves Portus UI)
-   Registry container (because dockerizing is the only way to have an up-to-date registry)
-   Local MariaDB server (backend db for Portus)
I got a working Portus' installation, with security and performance (the whole solution is running on a 1gb VM, and my 4 users didn't encounter any problem yet :D)

All data is stored under /data, which permits easy-to-configure backup.

Would someone find it useful if I document it ? (I mean, make something like a tutorial with some explanations on how this is working) 
I think it's a bit different from what @Djelibeybi suggests as I got as few containers as it's possible to have if you want an up-to-date solution.

**Comment by mssola** [comment]
@It4lik that would be great. We are already working on documenting different setups as explained in #1027. So, if you wrote such documentation we would link to it if possible :)

**Comment by It4lik** [comment]
I won't make any use of such a detailed documentation, I already got a technical doc at work. (but of course, I can't publish it).
If I make a more generic one, it would only be for you & the community :)

I didn't think this could be interesting for you or anyone else, since my setup is really old-school (one machine for multiple services, everything local, etc.). 
But, since you're interested, i'll work on it. I'll keep you informed ! 
I'll try to make it a bit more evolutive (db on different host, app server/reverse proxy clustering, make it more agnostic (do not force user to use Unicorn), etc.)

**Comment by mohan-raj** [comment]
@Djelibeybi I followed your steps in centos7. The registry and mariadb containers are running good. While running portus image, I am getting "**Waiting for mariadb to be ready in 5 seconds**" message, and failed with error "**Timeout reached, exiting with error**". 

I executed the following commands:

Registry
--------
docker run -d -p 5000:5000 --restart=always --name registry \
  -v /var/lib/registry/config.yml:/etc/docker/registry/config.yml \
  -v /var/lib/registry/data:/var/lib/registry \
  -v /var/lib/registry/certs:/certs \
  -v /var/lib/registry/auth:/auth \
registry:2

log
time="2017-02-13T07:37:08Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.7.3 instance.id=33254338-6ba5-4605-8c4e-bdb4730f2358 version=v2.6.0 
time="2017-02-13T07:37:09Z" level=info msg="listening on [::]:5000, tls" go.version=go1.7.3 instance.id=33254338-6ba5-4605-8c4e-bdb4730f2358 version=v2.6.0 

MariaDB
-------
docker run -d -p 3306:3306 --restart=always --name mariadb \
 -e MARIADB_SERVICE_HOST=mariadb \
 -e MARIADB_USER=portus \
 -e MARIADB_PASSWORD=portus \
 -e MARIADB_DATABASE=portus \
 -v /var/lib/registry/db:/var/lib/mysql \
 mariadb:latest

**log**
 [Warning] 'user' entry 'root@8331323e9e0f' ignored in --skip-name-resolve mode.
[Warning] 'proxies_priv' entry '@% root@8331323e9e0f' ignored in --skip-name-resolve mode.
mysqld: ready for connections.
Version: '10.1.21-MariaDB-1~jessie'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution 

Portus
------
docker run -d --restart=always --name portus \
 -v /var/lib/registry/certs:/certificates \
 -v /var/lib/registry/certs/domain.crt:/certificates/portus-ca.crt \
 -v /var/lib/registry/certs/domain.key:/secrets/portus.key \
 -v /var/lib/registry/portus/config-local.yml:/srv/Portus/config/config-local.yml \
 --link mariadb:mariadb \
 -e MARIADB_SERVICE_HOST=mariadb \
 -e MARIADB_USER=portus \
 -e MARIADB_PASSWORD=portus \
 -e MARIADB_DATABASE=portus \
 -e PORTUS_SECRET_KEY_BASE=$(openssl rand -hex 64) \
 -e PORTUS_PORTUS_PASSWORD=$(openssl rand -hex 64) \
 -p 443:443 \
 -p 80:80 \
opensuse/portus:2.0

Other than the "**Waiting for mariadb to be ready in 5 seconds**" this message, I am not getting any error message to debug. I am very new to docker. 
Could you point out what I missing in the configurations.

Thanks.

**Comment by Djelibeybi** [comment]
I'm afraid I don't know why Portus isn't starting in your case. Can you try starting Portus using `opensuse/portus:head` to see if using the latest version helps?

**Comment by Djelibeybi** [comment]
FYI, I've updated my repo to include an NGINX proxy so that Portus and the Registry are proxied instead of directly accessed. This has the added benefit of allowing both Portus and the Registry to work on standard HTTPS (port 443) so you don't need to remember to include `:5000` when logging into or pushing/pulling from the registry.

Makes for a far more seamless experience, IMO.

**Comment by rammaram06** [comment]
Hi @It4lik,  Did you get a chance to publish document on how to set it up on Centos? I'm also looking to set it up on single Centos\Redhat server.

**Comment by skyding1212** [comment]
Hi @mohan-raj  ,I have a same problem，how to be solved ？

**Comment by smile326** [comment]
i have the same problem on centos7.

Waiting for mariadb to be ready in 5 seconds
Starting portus_db_1 ... done
Starting portus_db_1 ... done
 failed, will retry
Waiting for mariadb to be ready in 5 seconds
Starting portus_db_1 ... done
Starting portus_db_1 ... done
 failed, will retry
Waiting for mariadb to be ready in 5 seconds
Starting portus_db_1 ... done
Starting portus_db_1 ... done
 failed, will retry
Waiting for mariadb to be ready in 5 seconds
Starting portus_db_1 ... done
Starting portus_db_1 ... done
 failed, will retry
Waiting for mariadb to be ready in 5 seconds
Starting portus_db_1 ... done
Starting portus_db_1 ... done
 failed, will retry
Waiting for mariadb to be ready in 5 seconds
Starting portus_db_1 ... done
Starting portus_db_1 ... done
 failed, will retry
Waiting for mariadb to be ready in 5 seconds
Starting portus_db_1 ... done
Starting portus_db_1 ... done
 failed, will retry
Waiting for mariadb to be ready in 5 seconds
Starting portus_db_1 ... done
Starting portus_db_1 ... done
 failed, will retry
Waiting for mariadb to be ready in 5 seconds
Starting portus_db_1 ... done
Starting portus_db_1 ... done
 failed, will retry
 [FAIL]
Timeout reached, exiting with error

do not know how to solve.

**Comment by patfrat** [comment]
Hello, it seems to be only wrong environment variables
Use this to launch the Portus docker

```
 -e PORTUS_PRODUCTION_HOST=mariadb \
 -e PORTUS_PRODUCTION_USERNAME=portus \
 -e PORTUS_PRODUCTION_PASSWORD=portus \
 -e PORTUS_PRODUCTION_DATABASE=portus \
```
instead of

```
-e MARIADB_SERVICE_HOST=mariadb 
-e MARIADB_USER=portus 
-e MARIADB_PASSWORD=portus 
-e MARIADB_DATABASE=portus 
```

**Comment by smile326** [comment]
@patfrat 
i do as you say,like this:
./compose-setup.sh -e 192.168.0.138 \
 -e PORTUS_PRODUCTION_HOST=mariadb \
 -e PORTUS_PRODUCTION_USERNAME=portus \
 -e PORTUS_PRODUCTION_PASSWORD=portus \
 -e PORTUS_PRODUCTION_DATABASE=portus 

but it still the same result.

**Comment by patfrat** [comment]
I use opensuse/portus:head

**Comment by patfrat** [comment]
```
docker run -d --restart=always --name portus 
-v /var/lib/registry/certs:/certificates 
-v /var/lib/registry/certs/domain.crt:/certificates/portus-ca.crt 
-v /var/lib/registry/certs/domain.key:/secrets/portus.key 
-v /var/lib/registry/portus/config-local.yml:/srv/Portus/config/config-local.yml 
--link mariadb:mariadb 
-e PORTUS_PRODUCTION_HOST=mariadb 
-e PORTUS_PRODUCTION_USERNAME=portus 
-e PORTUS_PRODUCTION_PASSWORD=portus 
-e PORTUS_PRODUCTION_DATABASE=portuss 
-e PORTUS_SECRET_KEY_BASE=$(openssl rand -hex 64) 
-e PORTUS_PORTUS_PASSWORD=$(openssl rand -hex 64) 
-p 443:443 
-p 80:80 
opensuse/portus:head
```

**Comment by patfrat** [comment]
I have also fixed the nginx/proxy.conf file

change that :

proxy_pass https://portus;
by
proxy_pass http://portus;

proxy_pass https://registry;
by
proxy_pass http://registry;

And change this upstream : 
upstream portus {
	server	portus:443;
}
to
upstream portus {
	server	portus:3000;
}

**Comment by patfrat** [comment]
This seems to be working and connect to the database without CSS compiling error for the Portus v2.2.and not v2.3 aka head

```
docker run -d --restart=always --name portus \
-v /var/lib/registry/certs/domain.crt:/certificates/portus-ca.crt 
-v /var/lib/registry/certs/domain.key:/secrets/portus.key 
-v /var/lib/registry/portus/config-local.yml:/srv/Portus/config/config-local.yml 
--link mariadb:mariadb \
-e MARIADB_SERVICE_HOST=mariadb \
-e MARIADB_USER=portus \
-e MARIADB_PASSWORD=portus \
-e MARIADB_DATABASE=portus \
-e PORTUS_SECRET_KEY_BASE=$(openssl rand -hex 64) \
-e PORTUS_PORTUS_PASSWORD=$(openssl rand -hex 64) \
opensuse/portus:2.2
```
It crashes first time but then working ...

**Comment by nowingfly** [comment]
I felt so frustrated that after followed most of the tutorials that can be found but still failed at last. It shows no error but nothing shown on the webpage when I access my private url, e.g. http://<my_domain>:5000.

Currently there is already **NO** **compose-setup.sh** in the latest code repository. So I first configured the **config/config.yml** as described at [http://port.us.org/docs/Configuring-Portus.html](http://port.us.org/docs/Configuring-Portus.html) (make a copy config-local.yml of config.yml and make change in config-local.yml). Actually the main change made in config-local.yml is just **machine_fqdn.value**. The other change made is **source "https://rubygems.org"** to **source "http://rubygems.org"** in **Gemfile**.

Then in the Portus folder, type "docker-compose up" to initialize all images. After a long time wait, it seems everything is configured and created.
![docker_images](https://user-images.githubusercontent.com/2989998/33300205-0533f8dc-d42a-11e7-8eaa-d73498cafbe9.jpeg)
And then type "docker-compose up" again to launch the environment.
![docker_containers](https://user-images.githubusercontent.com/2989998/33300225-1a0fd294-d42a-11e7-8f73-9c9ae43d5b02.jpeg)

But nothing shown but a big white webpage when typing the url. Anything wrong in my steps? Please help.

**Comment by vitoravelino** [comment]
Did you try `http://<your_domain>:3000`? In port 5000 it's supposed to be a blank page because it's the registry and not Portus web app.

And sorry for the outdated content mentioning the `compose-setup.sh` thing. We need to update that.

**Comment by nowingfly** [comment]
Thanks so much @vitoravelino . Now I can see the portus ui, but was blocked out to enjoy it. 

I have enabled the ldap authentication and saw the login ui as shown below:
<img width="496" alt="ldap_login" src="https://user-images.githubusercontent.com/2989998/33369471-abeb2c1c-d52f-11e7-895b-fb1303f38a7f.png">

After typing the username and password kept in ldap server, I met the following issue:
<img width="933" alt="ldap_error" src="https://user-images.githubusercontent.com/2989998/33369511-c5bcf562-d52f-11e7-98cc-57589168f410.png">

And the terminal showed the log as below:
<img width="1081" alt="ldap_log" src="https://user-images.githubusercontent.com/2989998/33369553-d9630b74-d52f-11e7-8cfa-4a0c6446af0a.png">

The ldap authentication is enabled via config/config-local.yml (some comments was stripped to shorten the paste):
<img width="619" alt="ldap_conf" src="https://user-images.githubusercontent.com/2989998/33369924-ff66371e-d530-11e7-946c-63c7353c27c9.png">

It seems that the portus has a problem to bind to the ldap server, but I can successfully get information from the ldap server in command line:
`
ldapsearch -h "localhost" -D "cn=info system,ou=People,dc=myrepo,dc=com" -w "PortusPass$" -b "ou=People,dc=myrepo,dc=com" -x "uid=portus"
`

Anything wrong? I can find a similar topic at [https://github.com/SUSE/Portus/issues/798](https://github.com/SUSE/Portus/issues/798), but it seems that nothing resolved.

**Comment by nowingfly** [comment]
I can login to the portus after disable ldap and create the first admin account. I can create more namespaces but failed to create new members.

It's so wired that the message "User cannot be found" always prompted for adding a new member. The log is shown as below:
>   Parameters: {"utf8"=>"✓", "team_user"=>{"team"=>"dev", "role"=>"contributor", "user"=>"demo"}, "commit"=>"Add"}
  User Load (0.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 2  ORDER BY `users`.`id` ASC LIMIT 1
   (0.2ms)  SELECT COUNT(*) FROM `registries`
  Team Load (0.2ms)  SELECT  `teams`.* FROM `teams` WHERE `teams`.`name` = 'dev' LIMIT 1
  User Load (0.2ms)  SELECT  `users`.* FROM `users` WHERE `users`.`username` = 'demo' LIMIT 1
  Rendered team_users/create.js.erb (0.3ms)
Completed 422 Unprocessable Entity in 10ms (Views: 3.5ms | ActiveRecord: 0.9ms)

The branch I checked out is master. Can anyone successfully setup the portus? Is there a simple way to set it up?

**Comment by nowingfly** [comment]
This issue can be closed now for I have switched to vmware's harbor project. It really works quite well for me.

**Comment by mssola** [comment]
The docker-compose setup from the `examples` directory should be a pretty good way to start. You can check the [How to deploy](http://port.us.org/docs/deploy.html) page of the documentation for more info (e.g. instructions on how to install with Helm and Kubernetes).
